# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75fd82f9533cbf68f6cf1e9b1ed2bdb291e16d9b0d8c89cd9fab25552601402cb7159a1a797e81397f528996b3d3e8861e4db816d490fcd97c6ab75dd365cebc

test:
  secret_key_base: 6fecaa3cbdff00255bed98bf04e51656f71e55f54742e23f6ae4f060d7a0e26b81669cc99a23f53a670c1b4c42fbd87a2bcaf8896398c8ad98ac0f297e4f0973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
