# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944a5577666c6eff912cb867523978d7944c6bfe40bc9de7f4152e256e992d3a208ffd456ff05acc30d71d0bed5ef1453964504c2b58f6b887b241cdd19db908

test:
  secret_key_base: ff108539b6e7655f417e5c320a706a489f001ff8206bda20a8e2c328fb285948d8906357c1dc731e45fd7702cf2fa6aae7e3b1f012b6add527745b34b6b76dd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
